//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        public int IDAlbum { get; set; }
        public string Adi { get; set; }
        public string Resim { get; set; }
        public int IndirimOrani { get; set; }
        public int SanatciID { get; set; }
        public string SanatciAdi { get; set; }
        public int TurID { get; set; }
        public string Turu { get; set; }
        public bool SilindiMi { get; set; }
        public decimal Fiyati { get; set; }
    
        public virtual sanatci sanatci { get; set; }
    }
}
