//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siparis()
        {
            this.siparis_liste = new HashSet<siparis_liste>();
        }
    
        public int IDSiparis { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string KullaniciMail { get; set; }
        public bool Durumu { get; set; }
    
        public virtual kullanici kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparis_liste> siparis_liste { get; set; }
    }
}
