//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis_liste
    {
        public int IDListe { get; set; }
        public int SiparisID { get; set; }
        public int AlbumID { get; set; }
        public string AlbumAdi { get; set; }
        public int Adet { get; set; }
        public decimal Tutar { get; set; }
    
        public virtual siparis siparis { get; set; }
    }
}
